# Generated by Django 3.1.7 on 2021-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=32)),
                ('rollno', models.IntegerField()),
                ('firstname', models.TextField(max_length=32)),
                ('lastname', models.TextField(max_length=32)),
                ('mathmarks', models.IntegerField()),
                ('physicsmarks', models.IntegerField()),
                ('chemistrymarks', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
